[project]
name = "cada-async"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.13",
    "fastrtc>=0.0.28",
    "gradio>=5.34.2",
    "onnxruntime>=1.22.0",
]
